version: '3.8'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kirillkiselev/foodgram_backend
    env_file: .env
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: kirillkiselev/foodgram_frontend
    command: cp -r /app/build/. /static_frontend/
    volumes:
      - static_frontend:/static_frontend/
  nginx:
    image: kirillkiselev/foodgram_nginx
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/static_django/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media/
      - static_frontend:/static_frontend/
    depends_on:
      - backend
      - db