version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:

  db:
    image: postgres:13
    env_file: ../.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram_backend
    build: ../backend/
    env_file: ../.env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
      - ../data:/app/data/
    depends_on:
      - db
  frontend:
    container_name: foodgram_frontend
    build: ../frontend
    volumes:
      - static_frontend:/static_frontend/
  nginx:
    container_name: foodgram_nginx
    build: ../infra/
    env_file: ../.env
    ports:
      - "8000:80"
    volumes:
      - static:/static_django/
      - media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_frontend:/static_frontend/
    depends_on:
      - backend
      - db
