version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kirillkiselev/foodgram_backend
    env_file: ../.env
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
  frontend:
    env_file: ../.env
    image: kirillkiselev/foodgram-front
    command: cp -r /app/result_build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: kirillkiselev/foodgram-proxy
    env_file: ../.env
    ports:
      - "80:80"
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - db
