version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: infra-backend
    env_file: ../.env
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
  frontend:
    env_file: ../.env
    image: infra-frontend
    command: cp -r /app/result_build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.25.4-alpine
    env_file: ../.env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - db