# Generated by Django 4.2.13 on 2024-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsrecipes',
            options={'verbose_name': 'Рецепт-ингредиент', 'verbose_name_plural': 'Рецепты-ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='tagsrecipes',
            options={'verbose_name': 'Рецепт-тег', 'verbose_name_plural': 'Рецепты-теги'},
        ),
        migrations.AddField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
