# Generated by Django 4.2.13 on 2024-05-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follows_follows_unique_user_follower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
